version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: ${POSTGRES_CONTAINER_NAME}
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - sistema-network

networks:
  sistema-network:
    driver: bridge